/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_tpm.h"
#include "fsl_gpio.h"
#include "fsl_port.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define PWM_PERIPHERAL TPM0
/* Definition of the clock source frequency */
#define PWM_CLOCK_SOURCE 8000000UL
/* PWM interrupt vector ID (number). */
#define PWM_IRQN TPM0_IRQn
/* PWM interrupt handler identifier. */
#define PWM_IRQHANDLER TPM0_IRQHandler
/* Alias for GPIOC peripheral */
#define MODE_GPIO GPIOC
/* Alias for PORTC */
#define MODE_PORT PORTC
/* MODE interrupt vector ID (number). */
#define MODE_IRQN PORTC_PORTD_IRQn
/* MODE interrupt handler identifier. */
#define MODE_IRQHANDLER PORTC_PORTD_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const tpm_config_t PWM_config;
extern gpio_pin_config_t MODE_config[2];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
