/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 Receive Data Source Select: UART_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 Transmit Data Source Select: UART0_TX pin */

/*! @name PORTA1 (number 23), J1[2]/D0/UART1_RX_TGTMCU
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PERIPHERAL UART0                 /*!<@brief Device name: UART0 */
#define BOARD_INITPINS_DEBUG_UART_RX_SIGNAL RX                        /*!<@brief UART0 signal: RX */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA                       /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U                           /*!<@brief PORTA pin index: 1 */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_NAME UART0_RX                /*!<@brief Pin name */
#define BOARD_INITPINS_DEBUG_UART_RX_LABEL "J1[2]/D0/UART1_RX_TGTMCU" /*!<@brief Label */
#define BOARD_INITPINS_DEBUG_UART_RX_NAME "DEBUG_UART_RX"             /*!<@brief Identifier name */
                                                                      /* @} */

/*! @name PORTA2 (number 24), J1[4]/D1/UART1_TX_TGTMCU
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PERIPHERAL UART0                 /*!<@brief Device name: UART0 */
#define BOARD_INITPINS_DEBUG_UART_TX_SIGNAL TX                        /*!<@brief UART0 signal: TX */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA                       /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U                           /*!<@brief PORTA pin index: 2 */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_NAME UART0_TX                /*!<@brief Pin name */
#define BOARD_INITPINS_DEBUG_UART_TX_LABEL "J1[4]/D1/UART1_TX_TGTMCU" /*!<@brief Label */
#define BOARD_INITPINS_DEBUG_UART_TX_NAME "DEBUG_UART_TX"             /*!<@brief Identifier name */
                                                                      /* @} */

/*! @name PORTC3 (number 46), SW1
  @{ */
#define BOARD_INITPINS_SW1_PERIPHERAL GPIOC                  /*!<@brief Device name: GPIOC */
#define BOARD_INITPINS_SW1_SIGNAL GPIO                       /*!<@brief GPIOC signal: GPIO */
#define BOARD_INITPINS_SW1_GPIO GPIOC                        /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SW1_GPIO_PIN 3U                       /*!<@brief PORTC pin index: 3 */
#define BOARD_INITPINS_SW1_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SW1_PIN 3U                            /*!<@brief PORTC pin index: 3 */
#define BOARD_INITPINS_SW1_CHANNEL 3                         /*!<@brief GPIOC GPIO channel: 3 */
#define BOARD_INITPINS_SW1_PIN_NAME PTC3                     /*!<@brief Pin name */
#define BOARD_INITPINS_SW1_LABEL "SW1"                       /*!<@brief Label */
#define BOARD_INITPINS_SW1_NAME "SW1"                        /*!<@brief Identifier name */
#define BOARD_INITPINS_SW1_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                             /* @} */

/*! @name PORTC1 (number 44), J4[12]/A5
  @{ */
#define BOARD_INITPINS_NIXIE_PERIPHERAL TPM0   /*!<@brief Device name: TPM0 */
#define BOARD_INITPINS_NIXIE_SIGNAL CH         /*!<@brief TPM0 signal: CH */
#define BOARD_INITPINS_NIXIE_PORT PORTC        /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_NIXIE_PIN 1U            /*!<@brief PORTC pin index: 1 */
#define BOARD_INITPINS_NIXIE_CHANNEL 0         /*!<@brief TPM0 channel: 0 */
#define BOARD_INITPINS_NIXIE_PIN_NAME TPM0_CH0 /*!<@brief Pin name */
#define BOARD_INITPINS_NIXIE_LABEL "J4[12]/A5" /*!<@brief Label */
#define BOARD_INITPINS_NIXIE_NAME "NIXIE"      /*!<@brief Identifier name */
                                               /* @} */

/*! @name PORTE29 (number 17), LED_RED
  @{ */
#define BOARD_INITPINS_LED_RED_PERIPHERAL TPM0   /*!<@brief Device name: TPM0 */
#define BOARD_INITPINS_LED_RED_SIGNAL CH         /*!<@brief TPM0 signal: CH */
#define BOARD_INITPINS_LED_RED_PORT PORTE        /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED_RED_PIN 29U           /*!<@brief PORTE pin index: 29 */
#define BOARD_INITPINS_LED_RED_CHANNEL 2         /*!<@brief TPM0 channel: 2 */
#define BOARD_INITPINS_LED_RED_PIN_NAME TPM0_CH2 /*!<@brief Pin name */
#define BOARD_INITPINS_LED_RED_LABEL "LED_RED"   /*!<@brief Label */
#define BOARD_INITPINS_LED_RED_NAME "LED_RED"    /*!<@brief Identifier name */
                                                 /* @} */

/*! @name PORTE31 (number 19), LED_GRN
  @{ */
#define BOARD_INITPINS_LED_GREEN_PERIPHERAL TPM0   /*!<@brief Device name: TPM0 */
#define BOARD_INITPINS_LED_GREEN_SIGNAL CH         /*!<@brief TPM0 signal: CH */
#define BOARD_INITPINS_LED_GREEN_PORT PORTE        /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED_GREEN_PIN 31U           /*!<@brief PORTE pin index: 31 */
#define BOARD_INITPINS_LED_GREEN_CHANNEL 4         /*!<@brief TPM0 channel: 4 */
#define BOARD_INITPINS_LED_GREEN_PIN_NAME TPM0_CH4 /*!<@brief Pin name */
#define BOARD_INITPINS_LED_GREEN_LABEL "LED_GRN"   /*!<@brief Label */
#define BOARD_INITPINS_LED_GREEN_NAME "LED_GREEN"  /*!<@brief Identifier name */
                                                   /* @} */

/*! @name PORTD5 (number 62), J2[12]/D13/LED_BLUE
  @{ */
#define BOARD_INITPINS_LED_BLUE_PERIPHERAL TPM0             /*!<@brief Device name: TPM0 */
#define BOARD_INITPINS_LED_BLUE_SIGNAL CH                   /*!<@brief TPM0 signal: CH */
#define BOARD_INITPINS_LED_BLUE_PORT PORTD                  /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_BLUE_PIN 5U                      /*!<@brief PORTD pin index: 5 */
#define BOARD_INITPINS_LED_BLUE_CHANNEL 5                   /*!<@brief TPM0 channel: 5 */
#define BOARD_INITPINS_LED_BLUE_PIN_NAME TPM0_CH5           /*!<@brief Pin name */
#define BOARD_INITPINS_LED_BLUE_LABEL "J2[12]/D13/LED_BLUE" /*!<@brief Label */
#define BOARD_INITPINS_LED_BLUE_NAME "LED_BLUE"             /*!<@brief Identifier name */
                                                            /* @} */

/*! @name PORTB16 (number 39), E1/TSI0_CH9
  @{ */
#define BOARD_INITPINS_TSI_ELECTRODE_1_PERIPHERAL TSI0        /*!<@brief Device name: TSI0 */
#define BOARD_INITPINS_TSI_ELECTRODE_1_SIGNAL CH              /*!<@brief TSI0 signal: CH */
#define BOARD_INITPINS_TSI_ELECTRODE_1_PORT PORTB             /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_TSI_ELECTRODE_1_PIN 16U                /*!<@brief PORTB pin index: 16 */
#define BOARD_INITPINS_TSI_ELECTRODE_1_CHANNEL 9              /*!<@brief TSI0 channel: 9 */
#define BOARD_INITPINS_TSI_ELECTRODE_1_PIN_NAME TSI0_CH9      /*!<@brief Pin name */
#define BOARD_INITPINS_TSI_ELECTRODE_1_LABEL "E1/TSI0_CH9"    /*!<@brief Label */
#define BOARD_INITPINS_TSI_ELECTRODE_1_NAME "TSI_ELECTRODE_1" /*!<@brief Identifier name */
                                                              /* @} */

/*! @name PORTB17 (number 40), E1/TSI0_CH10
  @{ */
#define BOARD_INITPINS_TSI_ELECTRODE_2_PERIPHERAL TSI0        /*!<@brief Device name: TSI0 */
#define BOARD_INITPINS_TSI_ELECTRODE_2_SIGNAL CH              /*!<@brief TSI0 signal: CH */
#define BOARD_INITPINS_TSI_ELECTRODE_2_PORT PORTB             /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_TSI_ELECTRODE_2_PIN 17U                /*!<@brief PORTB pin index: 17 */
#define BOARD_INITPINS_TSI_ELECTRODE_2_CHANNEL 10             /*!<@brief TSI0 channel: 10 */
#define BOARD_INITPINS_TSI_ELECTRODE_2_PIN_NAME TSI0_CH10     /*!<@brief Pin name */
#define BOARD_INITPINS_TSI_ELECTRODE_2_LABEL "E1/TSI0_CH10"   /*!<@brief Label */
#define BOARD_INITPINS_TSI_ELECTRODE_2_NAME "TSI_ELECTRODE_2" /*!<@brief Identifier name */
                                                              /* @} */

/*! @name PORTC5 (number 50), J4[9]/CMP_OUT
  @{ */
#define BOARD_INITPINS_DEVICE_SELECT_PERIPHERAL GPIOC                  /*!<@brief Device name: GPIOC */
#define BOARD_INITPINS_DEVICE_SELECT_SIGNAL GPIO                       /*!<@brief GPIOC signal: GPIO */
#define BOARD_INITPINS_DEVICE_SELECT_GPIO GPIOC                        /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_DEVICE_SELECT_GPIO_PIN 5U                       /*!<@brief PORTC pin index: 5 */
#define BOARD_INITPINS_DEVICE_SELECT_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_DEVICE_SELECT_PIN 5U                            /*!<@brief PORTC pin index: 5 */
#define BOARD_INITPINS_DEVICE_SELECT_CHANNEL 5                         /*!<@brief GPIOC GPIO channel: 5 */
#define BOARD_INITPINS_DEVICE_SELECT_PIN_NAME PTC5                     /*!<@brief Pin name */
#define BOARD_INITPINS_DEVICE_SELECT_LABEL "J4[9]/CMP_OUT"             /*!<@brief Label */
#define BOARD_INITPINS_DEVICE_SELECT_NAME "DEVICE_SELECT"              /*!<@brief Identifier name */
#define BOARD_INITPINS_DEVICE_SELECT_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
